spring:
  profiles:
    active:
      dev

---
spring:
  profiles: dev
  application:
    name: springcloud-config
server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
---
spring:
  profiles: prod
  application:
    name: springcloud-config
server:
  port: 10002
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/